#!/bin/bash

if [ $# -eq 0 ]; then
    echo "[usage]ngx <start|stop>"
    exit -1
fi

if [ $1 == "start" ]; then
    echo "nginx start ..."
	rm -rf $HOME/logs/nginx/*
	$NGINX_HOME/sbin/nginx
	echo "ok!"
elif [ $1 == "stop" ]; then
    echo "nginx stop ..."
	kill -15 `cat $NGINX_HOME/logs/nginx.pid`
	echo "done!"
fi
